<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/%5B02192019_1%5D_Tensorflow_Intro_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
ts_c = tf.constant(2,name='ts_c')
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [0]:
ts_x=tf.Variable(ts_c+5,name='ts_x')
ts_x

Instructions for updating:
Colocations handled automatically by placer.


<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

In [0]:
sess=tf.Session()

In [0]:
init=tf.global_variables_initializer()
sess.run(init)

In [0]:
print('ts_c=',sess.run(ts_c))

ts_c= 2


In [0]:
print('ts_x',sess.run(ts_x))

ts_x 7


In [0]:
sess.close()

In [0]:
# Automatically Close Sess, Since it leave the calc block
a = tf.constant(2,name='a')
b = tf.Variable(a+5,name='b')
with tf.Session() as sess:
  init=tf.global_variables_initializer()
  print('a=',sess.run(a))
  print('a=',sess.run(a+5))
  #print('b=',sess.run(b))

a= 2
a= 7


In [0]:
width=tf.placeholder("int32")
height=tf.placeholder("int32")
area=tf.multiply(width,height)

In [0]:
sess=tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print("area=",sess.run(area,feed_dict={width:6, height:8}))
sess.close()

area= 48


In [0]:
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print("area=",sess.run(area,feed_dict={width:6, height:8}))

area= 48


In [0]:
import tensorflow as tf
width=tf.placeholder("int32",name='width')
height=tf.placeholder("int32",name='height')
area=tf.multiply(width,height,name='area')

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print("area=",sess.run(area,feed_dict={width:6, height:8}))
  
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area',sess.graph)

area= 48


In [0]:
#tensorboard --logdir=log\area

In [0]:
ts_X=tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X=sess.run(ts_X)
  print(X)
  print(X.shape)

[0.4 0.2 0.4]
(3,)


In [0]:
W=tf.Variable([[-0.5,-0.2],
              [-0.3,0.4],
              [-0.5,0.2]])
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  W_array=sess.run(W)
  print(W_array)
  print(W_array.shape)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]
(3, 2)


In [0]:
X=tf.Variable([[0.4,0.2,0.4]])

W=tf.Variable([[-0.5,-0.2],
              [-0.3,0.4],
              [-0.5,0.2]])

XW = tf.matmul(X,W)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print(sess.run(XW))

[[-0.46000004  0.08      ]]


In [0]:
b=tf.Variable([[0.46,-0.08]])

Sum = XW + b
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print(sess.run(Sum))

[[-2.9802322e-08  0.0000000e+00]]
