<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/%5B02172019_1%5D_Keras_Titanic_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocess

In [0]:
import urllib.request
import os

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

url='http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.xls'
filepath = '/content/gdrive/My Drive/Keras/titanic3.xls'
if not os.path.isfile(filepath):
  result=urllib.request.urlretrieve(url,filepath)
  print('download:',result)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
download: ('/content/gdrive/My Drive/Keras/titanic3.xls', <http.client.HTTPMessage object at 0x7fb99aed5b38>)


In [0]:
import numpy
import pandas as pd

In [0]:
all_df=pd.read_excel(filepath)

In [6]:
all_df[:5]

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [0]:
cols=['survived','name','pclass','sex','age','sibsp','parch','fare','embarked']
all_df=all_df[cols]

In [8]:
all_df[:5]

survived                                             name  pclass     sex  \
0         1                    Allen, Miss. Elisabeth Walton       1  female   
1         1                   Allison, Master. Hudson Trevor       1    male   
2         0                     Allison, Miss. Helen Loraine       1  female   
3         0             Allison, Mr. Hudson Joshua Creighton       1    male   
4         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  female   

       age  sibsp  parch      fare embarked  
0  29.0000      0      0  211.3375        S  
1   0.9167      1      2  151.5500        S  
2   2.0000      1      2  151.5500        S  
3  30.0000      1      2  151.5500        S  
4  25.0000      1      2  151.5500        S

In [0]:
# survived - 0:NO 1:YES
# pclass - 1:first 2:business 3:economy
# sibsp - number of wife, husband, siblings
# parch - number of parents, children
# embarked - C/Q/S

df=all_df.drop(['name'],axis=1)

In [11]:
df[:5]

survived  pclass     sex      age  sibsp  parch      fare embarked
0         1       1  female  29.0000      0      0  211.3375        S
1         1       1    male   0.9167      1      2  151.5500        S
2         0       1  female   2.0000      1      2  151.5500        S
3         0       1    male  30.0000      1      2  151.5500        S
4         0       1  female  25.0000      1      2  151.5500        S

In [13]:
  all_df.isnull().sum()

survived      0
name          0
pclass        0
sex           0
age         263
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [0]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [0]:
fare_mean=df['fare'].mean()
df['fare']=df['fare'].fillna(fare_mean)

In [0]:
df['sex']=df['sex'].map({'female':0,'male':1}).astype(int)

In [18]:
x_OneHot_df=pd.get_dummies(data=df,columns=['embarked'])
x_OneHot_df[:5]

survived  pclass  sex      age  sibsp  parch      fare  embarked_C  \
0         1       1    0  29.0000      0      0  211.3375           0   
1         1       1    1   0.9167      1      2  151.5500           0   
2         0       1    0   2.0000      1      2  151.5500           0   
3         0       1    1  30.0000      1      2  151.5500           0   
4         0       1    0  25.0000      1      2  151.5500           0   

   embarked_Q  embarked_S  
0           0           1  
1           0           1  
2           0           1  
3           0           1  
4           0           1

In [20]:
ndarray=x_OneHot_df.values
print(ndarray)

[[1. 1. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [0. 3. 1. ... 1. 0. 0.]
 [0. 3. 1. ... 1. 0. 0.]
 [0. 3. 1. ... 0. 0. 1.]]


In [21]:
ndarray.shape

(1309, 10)

In [22]:
ndarray[:5]

array([[  1.    ,   1.    ,   0.    ,  29.    ,   0.    ,   0.    ,
        211.3375,   0.    ,   0.    ,   1.    ],
       [  1.    ,   1.    ,   1.    ,   0.9167,   1.    ,   2.    ,
        151.55  ,   0.    ,   0.    ,   1.    ],
       [  0.    ,   1.    ,   0.    ,   2.    ,   1.    ,   2.    ,
        151.55  ,   0.    ,   0.    ,   1.    ],
       [  0.    ,   1.    ,   1.    ,  30.    ,   1.    ,   2.    ,
        151.55  ,   0.    ,   0.    ,   1.    ],
       [  0.    ,   1.    ,   0.    ,  25.    ,   1.    ,   2.    ,
        151.55  ,   0.    ,   0.    ,   1.    ]])

In [0]:
Label = ndarray[:,0]
Features = ndarray[:,1:]

In [26]:
Label[:5]

array([1., 1., 0., 0., 0.])

In [27]:
Features[:5]

array([[  1.    ,   0.    ,  29.    ,   0.    ,   0.    , 211.3375,
          0.    ,   0.    ,   1.    ],
       [  1.    ,   1.    ,   0.9167,   1.    ,   2.    , 151.55  ,
          0.    ,   0.    ,   1.    ],
       [  1.    ,   0.    ,   2.    ,   1.    ,   2.    , 151.55  ,
          0.    ,   0.    ,   1.    ],
       [  1.    ,   1.    ,  30.    ,   1.    ,   2.    , 151.55  ,
          0.    ,   0.    ,   1.    ],
       [  1.    ,   0.    ,  25.    ,   1.    ,   2.    , 151.55  ,
          0.    ,   0.    ,   1.    ]])

In [0]:
from sklearn import preprocessing

In [0]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaledFeatures=minmax_scale.fit_transform(Features)

In [31]:
scaledFeatures[:5]

array([[0.        , 0.        , 0.36116884, 0.        , 0.        ,
        0.41250333, 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.00939458, 0.125     , 0.22222222,
        0.2958059 , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.0229641 , 0.125     , 0.22222222,
        0.2958059 , 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.37369494, 0.125     , 0.22222222,
        0.2958059 , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.31106443, 0.125     , 0.22222222,
        0.2958059 , 0.        , 0.        , 1.        ]])

In [39]:
msk = numpy.random.rand(len(all_df))<0.8
print(msk)
print(all_df[:5])
train_df = all_df[msk]
test_df = all_df[~msk]

[ True  True  True ...  True  True False]
   survived                                             name  pclass     sex  \
0         1                    Allen, Miss. Elisabeth Walton       1  female   
1         1                   Allison, Master. Hudson Trevor       1    male   
2         0                     Allison, Miss. Helen Loraine       1  female   
3         0             Allison, Mr. Hudson Joshua Creighton       1    male   
4         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  female   

       age  sibsp  parch      fare embarked  
0  29.0000      0      0  211.3375        S  
1   0.9167      1      2  151.5500        S  
2   2.0000      1      2  151.5500        S  
3  30.0000      1      2  151.5500        S  
4  25.0000      1      2  151.5500        S  


In [41]:
print('total:',len(all_df),'train:',len(train_df),'test:',len(test_df))

total: 1309 train: 1051 test: 258
