<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/%5B02262019_1%5D_Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
NumPy is the fundamental package for scientific computing with Python. </br>
NumPy’s main object is the homogeneous multidimensional array.  
It is a table of elements (usually numbers), all of the **same type**, indexed by a tuple of positive integers.  
In NumPy dimensions are called **axes**.

### Concept of axis

Reference: 手把手打開資料分析大門
https://www.slideshare.net/tw_dsconf/python-83977705/61

In [0]:
# one axis
[1, 3, 5]  # 3 elements, it has a length of 3.

# 2 axes
[[ 1, 3, 5],
 [ 2, 4, 6]]  # The first axis has a length of 2, the second axis has a length of 3.

[[1, 3, 5], [2, 4, 6]]

NumPy’s array class is called ndarray. </br>
t is also known by the alias array. </br>
Note that numpy.array is not the same as the Standard Python Library class array. </br>
array, which only handles one-dimensional arrays and offers less functionality.

### Create ndarray

In [0]:
import numpy as np

# create 1 axis array
x = np.arange(3)

print(x)
print(type(x))  # <class 'numpy.ndarray'>

# check if ndarray type
isinstance(x, np.ndarray)  # True

# be explicitly specified type
y = np.arange(3, dtype='float64')  # [ 0.  1.  2.]
print(y)

[0 1 2]
<class 'numpy.ndarray'>
[0. 1. 2.]


In [0]:
import numpy as np

existed_list = [18, 15, 21, 10, 88, 76, 29, 20]

np_array = np.array(existed_list)
print(np_array)  # [18 15 21 10 88 76 29 20]

[18 15 21 10 88 76 29 20]


### Important attributes of  ndarray

In [0]:
import numpy as np

x = np.arange(3)
print(x)

# ndim - the number of axes (dimensions) of the array.
print(x.ndim)  # 1 dim

# shape - the dimensions of the array. 
# This is a tuple of integers indicating the size of the array in each dimension.
print(x.shape)  # (3, )

# size - the total number of elements of the array. 
print(x.size)  # 3

# dtype - the type of the elements in the array.
print(x.dtype)  # int64

[0 1 2]
1
(3,)
3
int64


### Axes reshape
Gives a new shape to an array without changing its data.

In [0]:
# reshape
x = np.arange(6)
print(x)  # [0 1 2 3 4 5]

new_shape = x.reshape(2, 3)
print(new_shape) # [[0 1 2]
                 #  [3 4 5]]

# equivalently
new_shape = np.reshape(x, (2, 3))    
    
    
# also can be one line to create and reshpae
y = np.arange(6).reshape(2, 3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


### Initial placeholder content

In [0]:
# np.zeros - full of zeros
np.zeros(3)  # array([ 0.,  0.,  0.])

np.zeros((2, 3))  # array([[ 0.,  0.,  0.],
                  #        [ 0.,  0.,  0.]])

    
# np.ones - full of ones
np.ones((2,3))  # array([[ 1.,  1.,  1.],
                #        [ 1.,  1.,  1.]])

    
# np.identity - a square array with ones on the main diagonal
np.identity(3)  # array([[ 1.,  0.,  0.],
                #        [ 0.,  1.,  0.],
                #        [ 0.,  0.,  1.]])


# By default, the dtype of the created array is float64.
# using dtype change the type
np.zeros(3, dtype=np.int16)

array([0, 0, 0], dtype=int16)

### Array Index

Array indexing refers to any use of the square brackets ( [ ] ) to index array values.

In [0]:
import numpy as np

# 1-D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[2]   # 2
x[-2]  # 4


# 2-D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 2]   # 2
x[1, -1]  # 5

5

### Array Slice & Stride

The slicing and striding works exactly the same way it does for lists except that they can be applied to multiple dimensions as well.

In [0]:
import numpy as np

# 1-D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1:5]   # [2, 3, 4]
x[:2]    # [0, 1]
x[1:5:2] # [1, 3]


# 2-D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 0:2]    #  [0, 1]
x[:, 1:]     # [[1, 2],
             #  [4, 5]]
x[::1, ::2]  # [[0, 2],
             #  [3, 5]]

array([[0, 2],
       [3, 5]])

### Boolean / Mask Index 
Boolean arrays must be of the same shape as the initial dimensions of the array being indexed.

In [0]:
import numpy as np

# 1-D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
condition = x<3
x[condition]      # [0, 1, 2]

x[condition] = 0
x                 # [0, 0, 0, 3, 4, 5]


# why called mask?

# original_x      # [ 0,    1,    2,   3,    4,    5]
# if <3, assign 0
print(condition)  # [ True  True  True False False False]
x                 # [ 0,    0,    0,   3,    4,    5]

[ True  True  True False False False]


array([0, 0, 0, 3, 4, 5])

### Concatenate
Join a sequence of arrays along an existing axis.

In [0]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])

np.concatenate((a, b), axis=0)  # [[1, 2, 3],
                                #  [4, 5, 6],
                                #  [7, 8, 9]]


c =  [[0], [0]]       
np.concatenate((a, c), axis=1)  # [[1, 2, 3, 0],
                                #  [4, 5, 6, 0]]

array([[1, 2, 3, 0],
       [4, 5, 6, 0]])

### Basic Operations

In [0]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print(b)

print(a + b)  # array([[6, 8], [10, 12]])
print(a - b)  # array([[-4, -4], [-4, -4]])
print(a * b)  # array([[5, 12], [21, 32]])
print(a / b)  # array([[0.2, 0.33333333], [0.42857143, 0.5]]

print(a - 1)  # array([[0, 1], [2, 3]])
print(a * 2)  # array([[2, 4], [6, 8]])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0 1]
 [2 3]]
[[2 4]
 [6 8]]


### Basic Linear Algebra

轉置矩陣：m \* n 矩陣在向量空間上轉置為 n \* m 矩陣  
逆矩陣：n \* n 矩陣 A 存在一個 n \* n 矩陣 B，使得 AB = BA = I

In [0]:
import numpy as np

# 轉置矩陣
a = np.array([[0, 1], 
              [2, 3]])

print(a.T)  #[[0, 2],
            # [1, 3]]

# 逆矩陣
inverse = np.linalg.inv(a)
print(inverse)             # [[-1.5, 0.5], 
                           #  [1,    0]]

# 內積 
print(np.dot(a, inverse))  # [[ 1.  0.]
                           #  [ 0.  1.]]

[[0 2]
 [1 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
[[1. 0.]
 [0. 1.]]


### Vector Stacking

In [0]:
import numpy as np

a = np.array([[0, 1], 
              [2, 3]])

b = np.array([[4, 5], 
              [6, 7]])

c = np.array([[8,  9], 
              [10, 11]])

# vertical
v = np.vstack((a, b, c))
print(v.shape)  # (6, 2)
print(v)

# horizontal
h = np.hstack((a, b, c))
print(h.shape)  # (2, 6)
print(h)

# stack 
s = np.stack([a, b, c], axis=0)
print(s.shape)  # (3, 2, 2)
print(s)

(6, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(2, 6)
[[ 0  1  4  5  8  9]
 [ 2  3  6  7 10 11]]
(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


# Practice

In [0]:
import numpy as np

In [0]:
#Q1. Create a vector with values ranging from 10 to 49 by np.arrange
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [0]:
#Q2. Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [0]:
#Q3. Create a 3x3x3 array with random values by np.random.random
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.22695507 0.86504851 0.59878227]
  [0.38991605 0.02518213 0.10369809]
  [0.81185779 0.34869894 0.21505829]]

 [[0.93562669 0.40286615 0.56280877]
  [0.9039477  0.68844671 0.93920283]
  [0.24355433 0.74595726 0.38064932]]

 [[0.82811501 0.85616972 0.02971228]
  [0.69629248 0.24051995 0.48245754]
  [0.92381118 0.19388004 0.55493613]]]


In [0]:
#Q4. Create a 10x10 array with random values and find the minimum and maximum values by np.min, np.max
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.006408873935625503 0.9947097667677726


In [0]:
#Q5. Add a border (filled with 0's) around an 3 * 3 matrix with 1 by np.pad
Z = np.ones((3, 3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
#Q6. Normalize a 5x5 random matrix by divide max number
Z = np.random.random((5, 5))
Z2 = Z / Z.max()
Zmax, Zmin = Z.max(), Z.min()
Z1 = (Z - Zmin) / (Zmax - Zmin)
print(Z1)
print(Z2)

[[0.76641969 0.71824909 0.19663785 0.90893762 0.81151074]
 [0.40061702 0.55237219 0.45160713 0.46935106 0.06348891]
 [0.73655241 0.52246309 0.39299378 0.4978577  0.60440133]
 [0.52576801 0.17352937 0.74018203 0.62178534 0.        ]
 [0.47427247 0.09567634 1.         0.61628521 0.317979  ]]
[[0.77059578 0.72328641 0.21100086 0.91056569 0.81488067]
 [0.41133317 0.56037516 0.46141164 0.47883834 0.08023244]
 [0.74126249 0.53100079 0.40384622 0.50683532 0.61147409]
 [0.53424663 0.18830554 0.74482722 0.6285473  0.01787863]
 [0.48367175 0.11184441 1.         0.6231455  0.3301726 ]]


In [0]:
#Q7. Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [0]:
#Q8. Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean masking all the number:  

#(1) which are not divisible by 3  
#(2) which are divisible by 5  
#(3) which are divisible by 3 and 5

A = np.array([3,4,6,10,24,89,45,43,46,99,100])
div3 = A[A%3 != 0]
print(div3)

div5 = A[A%5 == 0]
print(div5)

div15 = A[(A%3 == 0) & (A%5 == 0)]
print(div15)

[  4  10  89  43  46 100]
[ 10  45 100]
[45]


In [0]:
#Q9. Create random vector of size 10 and replace the maximum value by 0 (np.argmax)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.17538738 0.4719358  0.80023841 0.26523017 0.89444408 0.43300892
 0.12829829 0.59198644 0.         0.63480897]


In [0]:
#Q10. Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5, 5))
print(Z)
Z += np.arange(5)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
