<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/%5B03012019_4%5D_Cat_Dog_BingHung_L3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import os
import zipfile

# 將下載到的資料集解壓縮至/tmp
local_zip = '/content/gdrive/My Drive/Keras/PetImages.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/CatDog')
zip_ref.close()

In [0]:
'''
base_path =r'/content/CatDog'
for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.endswith(".jpg"):
             print(os.path.join(root, file))
'''
import numpy as np
#from PIL import Image
import cv2

cat_img_list=[]
cat_label_list=[]
dog_img_list=[]
dog_label_list=[]
base_path = r'/content/CatDog'
for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.endswith(".jpg"):
            filename = os.path.join(root, file)
            #file_size = os.path.getsize(filename)
            category_name = os.path.basename(root)  
            imarray = cv2.imread(filename,3)
            if category_name == 'Cat':
              cat_img_list.append(imarray)
              cat_label_list.append(category_name)
            elif category_name == "Dog":
              dog_img_list.append(imarray)
              dog_label_list.append(category_name)
            

In [0]:
'''
import cv2
img = cv2.imread('/content/CatDog/PetImages/Dog/2831.jpg')
cv2.imshow('image',img)
'''

In [12]:
print(cat_img_list[0])
#print(dog_img_list)
print(len(cat_img_list))
print(len(dog_img_list))

print(cat_label_list)
print(dog_label_list)
print(len(cat_label_list))
print(len(dog_label_list))

[[[176 159 150]
  [179 162 153]
  [182 165 156]
  ...
  [255 248 241]
  [253 244 235]
  [253 244 234]]

 [[179 162 153]
  [181 164 155]
  [184 167 158]
  ...
  [255 250 243]
  [252 245 236]
  [254 245 235]]

 [[184 167 158]
  [185 168 159]
  [186 169 160]
  ...
  [255 253 248]
  [255 247 240]
  [255 248 239]]

 ...

 [[ 10  11   7]
  [  9  10   6]
  [  7   8   4]
  ...
  [ 73  91 128]
  [ 77  96 133]
  [ 81 103 139]]

 [[  8   9   5]
  [  7   8   4]
  [  6   7   3]
  ...
  [ 75  93 130]
  [ 81 100 137]
  [ 85 107 143]]

 [[  6   7   3]
  [  5   6   2]
  [  5   6   2]
  ...
  [ 77  95 132]
  [ 84 103 140]
  [ 87 109 145]]]
12500
12500
Cat
Dog
3
3


In [14]:
import matplotlib.pyplot as plt
plt.imshow(cat_img_list[0])
plt.show()