<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/Numpy_(Numerical_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1> 1D ndarray**

**`Establish 1D ndarray with array() method`**

In [3]:
import numpy as np
x = np.array([1,2,3])
print(type(x))
print(x)

print(x[0])
print(x[1],x[2])

x[1]=10
print(x)

<class 'numpy.ndarray'>
[1 2 3]
1
2 3
[ 1 10  3]


In [5]:
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


In [6]:
x = np.array([1])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (1,)
x.size :  1


In [7]:
x = np.array([2,4,6],dtype=np.int8)
print("x.dtype : ", x.dtype)

x.dtype :  int8


In [9]:
x = np.array([1.1,2.3,3.6])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  float64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


**Establish 1D ndarray with zeros() method**

In [10]:
import numpy as np
x = np.zeros(5)
print(x)

x = np.zeros(5, dtype=np.int_)
print(x)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


**Establish 1D ndarray with ones() method**

In [11]:
import numpy as np
x = np.ones(5)
print(x)

x = np.ones(5, dtype=np.int32)
print(x)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


**Elementary arithmetic of Numpy**

In [12]:
import numpy as np
x = np.array([1,2,3])
y = x + 5
print(y)

[6 7 8]


In [13]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


In [14]:
z = x * y
print(z)

[ 4 10 18]


In [15]:
z = x / y
print(z)

[0.25 0.4  0.5 ]


**Relational operator of Numpy**

In [16]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,1,6])
z = x > y
print(z)

[False  True False]


**Slicing**

In [17]:
import numpy as np
x = np.array([1,2,3,4,5])

print(x[0:3])
print(x[1:4])
print(x[0:5:2])
print(x[-1])
print(x[1:])
print(x[:3])

[1 2 3]
[2 3 4]
[1 3 5]
5
[2 3 4 5]
[1 2 3]


**Concatenate**

In [18]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5]


In [19]:
import numpy as np
x = np.array([1,2,3])
z = np.concatenate((x,[4,5]))
print(z)

[1 2 3 4 5]


**Insert**

In [20]:
import numpy as np
x = np.array([1,2,3])
z = np.insert(x,2,9)
print(z)

[1 2 9 3]


In [21]:
import numpy as np
x = np.array([1,2,3])
z = np.insert(x,[0,2],[7,9])
print(z)

[7 1 2 9 3]


**Delete**

In [23]:
import numpy as np
x = np.array([1,2,3])
z = np.delete(x,2)
print(z)

[1 2]


In [24]:
import numpy as np
x = np.array([1,2,3])
z = np.delete(x,[0,2])
print(z)

[2]


**Inner Product**

In [26]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,1,6])

z = np.inner(x,y)
print(z)

z = np.dot(x,y)
print(z)

24
24


**Cross Product**

In [31]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.cross(x,y)
print(z)

[-3  6 -3]


**Outer Product**

In [32]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.outer(x,y)
print(z)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Iteration**

In [33]:
import numpy as np
sum = 0
x = np.array([88, 92, 90, 0, 0])
for data in x:
  sum += data
print(sum)

270


**<h1> 2D ndarray**

In [34]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(type(x))
print(x)

print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
x.dtype :  int64
x.itemsize :  8
x.ndim :  2
x.shape :  (2, 3)
x.size :  6


In [35]:
print(x[0])
print(x[0,])
print(x[0,:])

[1 2 3]
[1 2 3]
[1 2 3]


In [37]:
print(x[:,0])

[1 4]


**Slicing**

In [38]:
import numpy as np
x = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

print(x[0:3,0])
print("---------------------------------------------------------")

print(x[0:2,2:4])
print("---------------------------------------------------------")

print(x[:2])
print("---------------------------------------------------------")

print(x[1:])
print("---------------------------------------------------------")

[1 2 3]
---------------------------------------------------------
[[3 4]
 [4 5]]
---------------------------------------------------------
[[1 2 3 4]
 [2 3 4 5]]
---------------------------------------------------------
[[2 3 4 5]
 [3 4 5 6]]
---------------------------------------------------------


**Reshape**

In [39]:
import numpy as np
x = np.array([1,2,3,4,5,6])

y = x.reshape(2,3)
print(y)

z = x.reshape(3,2)
print(z)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


**Ravel**

In [41]:
import numpy as np
x = np.array([[1,2,3,4],[2,3,4,5]])
y = x.ravel()
print(y)

[1 2 3 4 2 3 4 5]


**Resize , original changed**

In [42]:
import numpy as np
x = np.array([[1,2,3,4],[2,3,4,5]])
x.resize(3,2)
print(x)

[[1 2]
 [3 4]
 [2 3]]


**Transpose**

In [47]:
import numpy as np
x = np.arange(8).reshape(4,2) #arange()
print(x)

y = x.transpose()
print(y)

y = x.T
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]
[[0 2 4 6]
 [1 3 5 7]]


**Split - hsplit(),vsplit()**

In [48]:
import numpy as np
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [49]:
y1,y2 = np.hsplit(x,2)
print(y1)
print(y2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [52]:
y1,y2,y3,y4 = np.hsplit(x,4)
print(y1)
print(y2)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]


In [53]:
y1,y2 = np.vsplit(x,2)
print(y1)
print(y2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


**Stack - hstack(),vstack(),column_stack(),row_stack()**

In [55]:
import numpy as np
x = np.arange(4).reshape(2,2)
print(x)

y = np.arange(4,8).reshape(2,2)
print(y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [57]:
z = np.hstack((x,y))
print(z)

[[0 1 4 5]
 [2 3 6 7]]


In [58]:
z = np.vstack((x,y))
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [59]:
z = np.column_stack((x,y))
print(z)

[[0 1 4 5]
 [2 3 6 7]]


In [60]:
z = np.row_stack((x,y))
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


**Multiplication (Inner Product)**

In [63]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.dot(x,y)
print(z)

[[19 22]
 [43 50]]


In [64]:
import numpy as np
x = np.array([[1,0,2],[-1,3,1]])
y = np.array([[3,1],[2,1],[1,0]])
z = x@y
print(z)

[[5 1]
 [4 2]]


**Iteration**

In [67]:
import numpy as np

A = 0
X = np.arange(1,101).reshape(10,10)
print(X)
print("-------------------------------------------------")

for x in X:
  print(x)
  A += x
print(type(A))
print("A = ", A)
print("-------------------------------------------------")

sum = 0
for a in A:
  sum += a
print(type(sum))
print("sum = ", sum)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
-------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]
<class 'numpy.ndarray'>
A =  [460 470 480 490 500 510 520 530 540 550]
-------------------------------------------------
<class 'numpy.int64'>
sum =  5050


**<h1> Linear Algebra**

In [70]:
#Quadratic equation
import numpy as np
r = np.roots([3,5,1])
print(r)

[-1.43425855 -0.23240812]


In [74]:
#Simultaneous Linear Equations
import numpy as np
coeff = np.array([[3,5],[2,3]])
deps = np.array([18,11])
ans = np.linalg.solve(coeff, deps)
print(ans)

# verify
y = np.dot(coeff,ans)
print(y)

# allclose
print(np.allclose(y, deps))

[1. 3.]
[18. 11.]
True


**<h1> Broadcast**

In [78]:
#Broadcast
import numpy as np
x = np.array([1,2,3])
y = 5
z = x + y
print(z)

r = [5]
s = x + r
print(s)
print("-------------------------------------------------------")

x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6]])
z = x + y
print(z)
print("-------------------------------------------------------")

x = np.array([1,2,3]).reshape(3,1)
y = np.ones(5)

z = x + y
print(z)

[6 7 8]
[6 7 8]
-------------------------------------------------------
[[2 4 6]
 [5 7 9]]
-------------------------------------------------------
[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


**<h1> Trigonometric Functions**

In [80]:
#Degrees and Radians
import numpy as np
rad = np.arange(12)*np.pi/6
print("rad : ", rad)

x = np.degrees(rad)
print("deg : ",x)

rad :  [0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653]
deg :  [  0.  30.  60.  90. 120. 150. 180. 210. 240. 270. 300. 330.]


In [82]:
#Degrees and Radians
import numpy as np
deg = np.arange(12)*30
x = np.radians(deg)
print("rad : ",x )

rad :  [0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653]


**<h1> Numpy Methods**

In [88]:
#prod()
print(np.prod([]))
print(np.prod([1,2,3]))
print(np.prod([[1,2],[3,4]]))
print(np.prod([[1,2],[3,4]],axis=0))
print(np.prod([[1,2],[3,4]],axis=1))
print(np.prod([[1,2],[3,4],[5,6]],axis=0))
print(np.prod([[1,2],[3,4],[5,6]],axis=1))

1.0
6
24
[3 8]
[ 2 12]
[15 48]
[ 2 12 30]


In [89]:
#sum()
print(np.sum([]))
print(np.sum([1,2,3]))
print(np.sum([1.1,2.2,3.3]))
print(np.sum([[1,2],[3,4]],axis=0))
print(np.sum([[1,2],[3,4]],axis=1))

0.0
6
6.6
[4 6]
[3 7]


In [90]:
#sum()
import numpy as np
X = np.arange(1,101).reshape(10,10)
A = np.sum(X, axis=0)
print("A = ",A)
sum = np.sum(X)
print("sum = ",sum)

A =  [460 470 480 490 500 510 520 530 540 550]
sum =  5050


In [92]:
#diff
x = np.array([1,4,7,0,5])
print(np.diff(x))
print(np.diff(x, n=2))

y = np.array([[1,4,6,10],[0,2,5,9]])
print(np.diff(y))
print(np.diff(y, axis=0))

[ 3  3 -7  5]
[  0 -10  12]
[[3 2 4]
 [2 3 4]]
[[-1 -2 -1 -1]]


In [94]:
#round()
print(np.around([[0.49],[1.82]]))
print(np.around([[0.49],[1.82]], decimals=1))

[[0.]
 [2.]]
[[0.5]
 [1.8]]


In [95]:
#rint()
print(np.rint([1.4,1.5,1.6,2.5]))

[1. 2. 2. 2.]


In [96]:
#floor()
print(np.floor([1.4,1.5,1.6,2.5]))

[1. 1. 1. 2.]


In [98]:
#ceil()
print(np.ceil([1.4,1.5,1.6,2.5]))

[2. 2. 2. 3.]


In [97]:
#trunc()
print(np.trunc([1.4,1.5,1.6,2.5]))

[1. 1. 1. 2.]


**<h1> Greatest Common Divisor & Lowest Common Multiple**

In [99]:
np.gcd(12,20)

4

In [100]:
np.lcm(12,20)

60

**<h1> Exponential Function & logarithmic Function**

In [123]:
np.negative([-3])

array([3])

In [124]:
np.absolute([-3])

array([3])

In [125]:
np.square([-3])

array([9])

In [126]:
np.sqrt([9])

array([3.])

In [128]:
np.sign([-10,5,0])

array([-1,  1,  0])

In [132]:
np.max([1,87,5])

87

In [133]:
np.min([1,87,5])

1