<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/Numpy_(Numerical_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Establish 1D ndarray with array() method`**

In [3]:
import numpy as np
x = np.array([1,2,3])
print(type(x))
print(x)

print(x[0])
print(x[1],x[2])

x[1]=10
print(x)

<class 'numpy.ndarray'>
[1 2 3]
1
2 3
[ 1 10  3]


In [5]:
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


In [6]:
x = np.array([1])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (1,)
x.size :  1


In [7]:
x = np.array([2,4,6],dtype=np.int8)
print("x.dtype : ", x.dtype)

x.dtype :  int8


In [9]:
x = np.array([1.1,2.3,3.6])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  float64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


Establish 1D ndarray with zeros() method

In [10]:
import numpy as np
x = np.zeros(5)
print(x)

x = np.zeros(5, dtype=np.int_)
print(x)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


Establish 1D ndarray with ones() method

In [11]:
import numpy as np
x = np.ones(5)
print(x)

x = np.ones(5, dtype=np.int32)
print(x)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
