<a href="https://colab.research.google.com/github/BingHung/AI/blob/master/Numpy_(Numerical_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1> 1D ndarray**

**`Establish 1D ndarray with array() method`**

In [3]:
import numpy as np
x = np.array([1,2,3])
print(type(x))
print(x)

print(x[0])
print(x[1],x[2])

x[1]=10
print(x)

<class 'numpy.ndarray'>
[1 2 3]
1
2 3
[ 1 10  3]


In [5]:
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


In [6]:
x = np.array([1])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  int64
x.itemsize :  8
x.ndim :  1
x.shape :  (1,)
x.size :  1


In [7]:
x = np.array([2,4,6],dtype=np.int8)
print("x.dtype : ", x.dtype)

x.dtype :  int8


In [9]:
x = np.array([1.1,2.3,3.6])
print("x.dtype : ", x.dtype)
print("x.itemsize : ", x.itemsize)
print("x.ndim : ", x.ndim)
print("x.shape : ", x.shape)
print("x.size : ", x.size)

x.dtype :  float64
x.itemsize :  8
x.ndim :  1
x.shape :  (3,)
x.size :  3


**Establish 1D ndarray with zeros() method**

In [10]:
import numpy as np
x = np.zeros(5)
print(x)

x = np.zeros(5, dtype=np.int_)
print(x)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


**Establish 1D ndarray with ones() method**

In [11]:
import numpy as np
x = np.ones(5)
print(x)

x = np.ones(5, dtype=np.int32)
print(x)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


**Elementary arithmetic of Numpy**

In [12]:
import numpy as np
x = np.array([1,2,3])
y = x + 5
print(y)

[6 7 8]


In [13]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


In [14]:
z = x * y
print(z)

[ 4 10 18]


In [15]:
z = x / y
print(z)

[0.25 0.4  0.5 ]


**Relational operator of Numpy**

In [16]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,1,6])
z = x > y
print(z)

[False  True False]


**Slicing**

In [17]:
import numpy as np
x = np.array([1,2,3,4,5])

print(x[0:3])
print(x[1:4])
print(x[0:5:2])
print(x[-1])
print(x[1:])
print(x[:3])

[1 2 3]
[2 3 4]
[1 3 5]
5
[2 3 4 5]
[1 2 3]


**Concatenate**

In [18]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5]


In [19]:
import numpy as np
x = np.array([1,2,3])
z = np.concatenate((x,[4,5]))
print(z)

[1 2 3 4 5]


**Insert**

In [20]:
import numpy as np
x = np.array([1,2,3])
z = np.insert(x,2,9)
print(z)

[1 2 9 3]


In [21]:
import numpy as np
x = np.array([1,2,3])
z = np.insert(x,[0,2],[7,9])
print(z)

[7 1 2 9 3]


**Delete**

In [23]:
import numpy as np
x = np.array([1,2,3])
z = np.delete(x,2)
print(z)

[1 2]


In [24]:
import numpy as np
x = np.array([1,2,3])
z = np.delete(x,[0,2])
print(z)

[2]


**Inner Product**

In [26]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,1,6])

z = np.inner(x,y)
print(z)

z = np.dot(x,y)
print(z)

24
24


**Cross Product**

In [31]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.cross(x,y)
print(z)

[-3  6 -3]


**Outer Product**

In [32]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.outer(x,y)
print(z)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Iteration**

In [33]:
import numpy as np
sum = 0
x = np.array([88, 92, 90, 0, 0])
for data in x:
  sum += data
print(sum)

270
